#!/bin/bash

set -x

# make riscv
echo "-- Building for RISCV."
cmake -Bbuild-riscv -DCMAKE_C_COMPILER=riscv64-unknown-linux-gnu-gcc
cd build-riscv
make clean
make
cd ..

# copy to testenv
sudo mount testenv/rootfs.ext2 /mnt/rvdisk
sudo cp build-riscv/bin/demo /mnt/rvdisk/root/
sudo cp build-riscv/bin/l1pp_datacollect /mnt/rvdisk/root/
sudo cp build-riscv/prototypes/fork_to_same_cpu/prototype_fork_to_same_cpu /mnt/rvdisk/root/
sudo umount /mnt/rvdisk
