#!/bin/bash

# make default
echo "-- Building for native architecture of your current system."
cmake -Bbuild-default -DBUILD_TESTS=ON -DCMAKE_BUILD_TYP=Debug
cd build-default
make
make test
cd ..

# make riscv
echo "-- Building for RISCV."
cmake -Bbuild-riscv -DCMAKE_C_COMPILER=riscv64-unknown-linux-gnu-gcc
cd build-riscv
make clean
make
cd ..
