#!/bin/bash

set -x

# make riscv
echo "-- Building for RISCV."
cmake -Bbuild-riscv -DCMAKE_C_COMPILER=riscv64-unknown-linux-gnu-gcc
cd build-riscv
make clean
make
cd ..

# copy to testenv
sudo mount testenv/rootfs.ext2 /mnt/rvdisk
sudo cp build-riscv/src/demo /mnt/rvdisk/root/
sudo umount /mnt/rvdisk
