#ifndef __PROTOTYPE_PRIMESETGEN_H__
#define __PROTOTYPE_PRIMESETGEN_H__


#include <stdio.h>
#include <unistd.h>
#include <math.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * @brief      Defines CPU cache parameters. Isolated for this prototype.
 * 
 * This should be dynamically generated by reading sysfiles in
 * a Linux operating system. Exists as a struct within a cpu
 * struct. 
 */
struct cache_t {
    int ways; /*!< Number of cache ways. */
    int level; /*!< Level of this cache, eg L1. */
    int size; /*!< Size of cache, bytes. */
    int sets; /*!< Number of sets in this cache. */
    int linesize; /*!< Cache line size, bytes */
    int blocksize; /*!< The system block size, bytes. */
    char * type; /*!< String for instruction, data cache, etc. */
    // derived properties
    int numbits_Offset; /*!< Number of offset bits for an address in this system. */
    int numbits_Set; /*!< Number of bits used for indexing. */
    int numbits_Tag; /*!< Number of bits used for tag. */
    uint64_t mask_Offset; /*!< Masks to derive offset. */
    uint64_t mask_Set; /*!< Masks to derive set. */
    uint64_t mask_Tag; /*!< Masks to derive tag. */
};


#endif /* __PROTOTYPE_PRIMESETGEN_H__ */